### ISSUE TITLE
Add option for published / future / published + future posts

### ISSUE THREAD

**Issue by GaryJones** [GaryJones/calendar-category#1]
Add option for published / future / published + future posts - this allows scheduled posts (perhaps as events) to be shown too.

**Comment by charlesdevops** [comment]
Hello,
I'm using Calendar Category, but got stuck exactly on this issue. I suppose this project is not actively developed anymore, but I think I found a solution, tweaking the SQL queries:

1. Replace the instances of

`post_status = 'publish'`
with
`post_status IN ('publish','future')`

2. Change:
`AND post_date < '" . current_time( 'mysql' ) . '\'';`
to
`AND post_date != '" . current_time( 'mysql' ) . '\'';`

Worked for me.

**Comment by CarloMartini** [comment]
I tried to simply replace the instances of 

`post_status = 'publish'`
with
`post_status IN ('publish','future')`

In the SQL queries in the code, but that doesn't seem enough...
